in_metadata_path: "s3://ego4d-consortium-sharing/internal/egoexo_pilot/unc/T1/metadata.json"
in_videos: null
output_dir: "/private/home/miguelmartin/ego4d/ego4d_public/colmap_outputs"
name: null
aria_fps: 30
exo_fps: null
mobile_fps: null
include_aria: true
sync_exo_views: false
aria_use_sync_info: false
aria_walkthrough_start_sec: null
aria_walkthrough_end_sec: null
use_gpu: true
rot_mode: 1
camera_model: "OPENCV_FISHEYE"
exo_from_frame: 200
exo_to_frame: 300
frame_rate: 0.25
exo_frames: null
mobile_frames: null
aria_frames: null
colmap_bin: null
vrs_bin: null
run_colmap: false
force_download: false
download_video_files: true
take_id: null
video_source: null
